http://localhost:8001/api/quotes/2

###
ºPOST http://localhost:8001/api/quotes
Content-Type: application/json

    {
        "id": 111,
        "quote": "Helo from post request",
        "author": "Iker Macaya",
        "visual": "No image set",
        "prompt": "No Prompt here"
    }