# Generated by Django 5.1.4 on 2025-01-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('side', models.CharField(max_length=50)),
            ],
        ),
    ]
